### ISSUE TITLE
Thoughts on testing

### ISSUE THREAD

**Issue by davidrapson** [AndrewLowther/jQuery-Facet-Filter#4]
Just a couple of thoughts:
- It's odd to use expect, should and assert type at one in testing. They all provide similar APIs to the same thing so ideally one should be chosen as a preference. I like BDD/expect style FWIW
- I was thinking if it were worth mocking out some of the XHR functionality using sinon.js or whether that's not worth testing?

**Comment by AndrewLowther** [comment]
Agree with both of those things, my testing was basically me playing around with mocha, but it's definitely worth standardising to use one method of testing everything.

Mocking XHR is also very relevant indeed.
