### ISSUE TITLE
Set delay on request to prevent multiple requests

### ISSUE THREAD

**Issue by jonjhiggins** [AndrewLowther/jQuery-Facet-Filter#7]
Hi Andy

Recently I was asked to look at an issue involving the Facet Filter: after filtering on a date range, then selecting a "Today" button (which cleared the date ranges) the results would flash up all available results twice before showing the correct results. 

This was because when the "Today" button cleared the filters for the date ranges it sent off - returning requests for the cleared date ranges (i.e. all results) before displaying the correct results.

I fixed it in this instance by adding a timeout around the AJAX request, any changes to the filters would cancel pending requests - so only the most recent request so be sent and displayed.

Is this how you would of gone about it or is there a better way? Can submit pull request if it's useful.

Cheers
Jon

**Comment by AndrewLowther** [comment]
Hey Jon

Absolutely submit a pull request.

Cheers!
